version: '3.7'
services:
        app:
                image: hello-world-docker-compose
                build: .
                container_name: hello_world
                ports:
                        - target: 8080
                          published: 8080
                          protocol: tcp
        nginx:
                image: nginx:latest
                container_name: my_nginx
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp
                volumes:
                        - type: bind
                          source: ./src/main/resources/nginx/nginx.conf
                          target: /etc/nginx/nginx.conf
                          
